import axios from "axios";

import type { Scheduledata } from "@/utils/types";

// * Fetch complete 2022-2023 schedule
export async function getFullSchedule() {
  try {
    const { data } = await axios.get(
      "https://cdn.nba.com/static/json/staticData/scheduleLeagueV2_1.json",
      {
        headers: {
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
    return data.leagueSchedule.gameDates;
  } catch (error) {
    throw error;
  }
}

// * Fetch scheduled games of dateParam
export async function getSchedule(dateParam?: string) {
  // * @params
  // * dateParam:string| undefined consist of date in YYYYMMDD format
  try {
    // assigns dateParam to current date if it's undefined
    if (!dateParam) {
      const date = new Date();
      const year = date.getFullYear();
      const month = ("0" + (date.getMonth() + 1)).slice(-2);
      const day = ("0" + date.getDate()).slice(-2);

      const formattedDate = `${year}${month}${day}`;

      dateParam = formattedDate;
    }

    const { data } = await axios.get(
      "https://cdn.nba.com/static/json/staticData/scheduleLeagueV2_1.json"
    );

    const schedule = data.leagueSchedule.gameDates.find((i: Scheduledata) => {
      const date = new Date(i.gameDate);
      const year = date.getFullYear();
      const month = ("0" + (date.getMonth() + 1)).slice(-2);
      const day = ("0" + date.getDate()).slice(-2);

      const formattedDate = `${year}${month}${day}`;

      return formattedDate === dateParam;
    });

    return schedule;
  } catch (error) {
    throw error;
  }
}

// * Fetch single game from Schedule
// export async function getSingleGame(gameId: string){
//   const res:Scheduledata = await getFullSchedule()
//
//   const singleGame = res.games.
//
//
// }

// * Fetch single game data
export async function getGameStats(gameId: string) {
  // * @params
  // * gameId:string gameId string
  try {
    const url = `https://cdn.nba.com/static/json/liveData/boxscore/boxscore_${gameId}.json`;

    const { data } = await axios.get(url);

    return data.game;
  } catch (error) {
    throw error;
  }
}

// Fetch standings
export async function getStandings() {
  try {
    // const url = `https://stats.nba.com/stats/leaguestandingsv3?LeagueID=00&Season=2022-23&SeasonType=Regular%20Season&Section=overall`;
    // const { data: standings } = await axios.get(url, {
    //   headers: {
    //     Host: "stats.nba.com",
    //     "User-Agent":
    //       "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0",
    //     Accept: "application/json, text/plain, */*",
    //     "Accept-Language": "en-US,en;q=0.5",
    //     "Accept-Encoding": "gzip, deflate, br",
    //     "x-nba-stats-origin": "stats",
    //     "x-nba-stats-token": "true",
    //     Connection: "keep-alive",
    //     Referer: "https://stats.nba.com/",
    //     Pragma: "no-cache",
    //     "Cache-Control": "no-cache",
    //   },
    // });
    const standings = {
      season: "2022-23",
      standings: [
        {
          TeamID: 1610612743,
          TeamCity: "Denver",
          TeamName: "Nuggets",
          TeamSlug: "nuggets",
          Conference: "West",
          ConferenceRecord: "33-15",
          PlayoffRank: 1,
          Division: "Northwest",
          DivisionRank: 1,
          WINS: 52,
          LOSSES: 26,
          WinPCT: 0.667,
          HOME: "33-7 ",
          ROAD: "19-19",
          L10: "6-4  ",
          Last10Home: "7-3  ",
          Last10Road: "5-5  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612749,
          TeamCity: "Milwaukee",
          TeamName: "Bucks",
          TeamSlug: "bucks",
          Conference: "East",
          ConferenceRecord: "33-16",
          PlayoffRank: 1,
          Division: "Central",
          DivisionRank: 1,
          WINS: 56,
          LOSSES: 22,
          WinPCT: 0.718,
          HOME: "31-8 ",
          ROAD: "25-14",
          L10: "7-3  ",
          Last10Home: "7-3  ",
          Last10Road: "8-2  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612738,
          TeamCity: "Boston",
          TeamName: "Celtics",
          TeamSlug: "celtics",
          Conference: "East",
          ConferenceRecord: "31-17",
          PlayoffRank: 2,
          Division: "Atlantic",
          DivisionRank: 1,
          WINS: 54,
          LOSSES: 24,
          WinPCT: 0.692,
          HOME: "29-9 ",
          ROAD: "25-15",
          L10: "7-3  ",
          Last10Home: "8-2  ",
          Last10Road: "5-5  ",
          CurrentStreak: 2,
          strCurrentStreak: "W 2",
        },
        {
          TeamID: 1610612763,
          TeamCity: "Memphis",
          TeamName: "Grizzlies",
          TeamSlug: "grizzlies",
          Conference: "West",
          ConferenceRecord: "29-20",
          PlayoffRank: 2,
          Division: "Southwest",
          DivisionRank: 1,
          WINS: 49,
          LOSSES: 29,
          WinPCT: 0.628,
          HOME: "34-6 ",
          ROAD: "15-23",
          L10: "8-2  ",
          Last10Home: "9-1  ",
          Last10Road: "4-6  ",
          CurrentStreak: -1,
          strCurrentStreak: "L 1",
        },
        {
          TeamID: 1610612758,
          TeamCity: "Sacramento",
          TeamName: "Kings",
          TeamSlug: "kings",
          Conference: "West",
          ConferenceRecord: "31-17",
          PlayoffRank: 3,
          Division: "Pacific",
          DivisionRank: 1,
          WINS: 47,
          LOSSES: 31,
          WinPCT: 0.603,
          HOME: "23-17",
          ROAD: "24-14",
          L10: "6-4  ",
          Last10Home: "5-5  ",
          Last10Road: "9-1  ",
          CurrentStreak: -1,
          strCurrentStreak: "L 1",
        },
        {
          TeamID: 1610612755,
          TeamCity: "Philadelphia",
          TeamName: "76ers",
          TeamSlug: "sixers",
          Conference: "East",
          ConferenceRecord: "31-17",
          PlayoffRank: 3,
          Division: "Atlantic",
          DivisionRank: 2,
          WINS: 51,
          LOSSES: 27,
          WinPCT: 0.654,
          HOME: "28-11",
          ROAD: "23-16",
          L10: "5-5  ",
          Last10Home: "7-3  ",
          Last10Road: "6-4  ",
          CurrentStreak: -1,
          strCurrentStreak: "L 1",
        },
        {
          TeamID: 1610612739,
          TeamCity: "Cleveland",
          TeamName: "Cavaliers",
          TeamSlug: "cavaliers",
          Conference: "East",
          ConferenceRecord: "32-17",
          PlayoffRank: 4,
          Division: "Central",
          DivisionRank: 2,
          WINS: 49,
          LOSSES: 30,
          WinPCT: 0.62,
          HOME: "31-9 ",
          ROAD: "18-21",
          L10: "7-3  ",
          Last10Home: "7-3  ",
          Last10Road: "5-5  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612756,
          TeamCity: "Phoenix",
          TeamName: "Suns",
          TeamSlug: "suns",
          Conference: "West",
          ConferenceRecord: "28-20",
          PlayoffRank: 4,
          Division: "Pacific",
          DivisionRank: 2,
          WINS: 43,
          LOSSES: 35,
          WinPCT: 0.551,
          HOME: "26-12",
          ROAD: "17-23",
          L10: "6-4  ",
          Last10Home: "7-3  ",
          Last10Road: "5-5  ",
          CurrentStreak: 5,
          strCurrentStreak: "W 5",
        },
        {
          TeamID: 1610612752,
          TeamCity: "New York",
          TeamName: "Knicks",
          TeamSlug: "knicks",
          Conference: "East",
          ConferenceRecord: "31-19",
          PlayoffRank: 5,
          Division: "Atlantic",
          DivisionRank: 3,
          WINS: 46,
          LOSSES: 33,
          WinPCT: 0.582,
          HOME: "23-17",
          ROAD: "23-16",
          L10: "7-3  ",
          Last10Home: "8-2  ",
          Last10Road: "6-4  ",
          CurrentStreak: 4,
          strCurrentStreak: "W 4",
        },
        {
          TeamID: 1610612746,
          TeamCity: "LA",
          TeamName: "Clippers",
          TeamSlug: "clippers",
          Conference: "West",
          ConferenceRecord: "24-25",
          PlayoffRank: 5,
          Division: "Pacific",
          DivisionRank: 3,
          WINS: 41,
          LOSSES: 38,
          WinPCT: 0.519,
          HOME: "21-18",
          ROAD: "20-20",
          L10: "5-5  ",
          Last10Home: "6-4  ",
          Last10Road: "5-5  ",
          CurrentStreak: -2,
          strCurrentStreak: "L 2",
        },
        {
          TeamID: 1610612744,
          TeamCity: "Golden State",
          TeamName: "Warriors",
          TeamSlug: "warriors",
          Conference: "West",
          ConferenceRecord: "27-22",
          PlayoffRank: 6,
          Division: "Pacific",
          DivisionRank: 4,
          WINS: 41,
          LOSSES: 38,
          WinPCT: 0.519,
          HOME: "32-8 ",
          ROAD: "9-30 ",
          L10: "5-5  ",
          Last10Home: "9-1  ",
          Last10Road: "2-8  ",
          CurrentStreak: -1,
          strCurrentStreak: "L 1",
        },
        {
          TeamID: 1610612751,
          TeamCity: "Brooklyn",
          TeamName: "Nets",
          TeamSlug: "nets",
          Conference: "East",
          ConferenceRecord: "28-21",
          PlayoffRank: 6,
          Division: "Atlantic",
          DivisionRank: 4,
          WINS: 43,
          LOSSES: 35,
          WinPCT: 0.551,
          HOME: "22-16",
          ROAD: "21-19",
          L10: "4-6  ",
          Last10Home: "5-5  ",
          Last10Road: "5-5  ",
          CurrentStreak: 3,
          strCurrentStreak: "W 3",
        },
        {
          TeamID: 1610612748,
          TeamCity: "Miami",
          TeamName: "Heat",
          TeamSlug: "heat",
          Conference: "East",
          ConferenceRecord: "21-27",
          PlayoffRank: 7,
          Division: "Southeast",
          DivisionRank: 1,
          WINS: 41,
          LOSSES: 37,
          WinPCT: 0.526,
          HOME: "26-14",
          ROAD: "15-23",
          L10: "5-5  ",
          Last10Home: "7-3  ",
          Last10Road: "3-7  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612747,
          TeamCity: "Los Angeles",
          TeamName: "Lakers",
          TeamSlug: "lakers",
          Conference: "West",
          ConferenceRecord: "24-24",
          PlayoffRank: 7,
          Division: "Pacific",
          DivisionRank: 5,
          WINS: 40,
          LOSSES: 38,
          WinPCT: 0.513,
          HOME: "21-18",
          ROAD: "19-20",
          L10: "7-3  ",
          Last10Home: "6-4  ",
          Last10Road: "7-3  ",
          CurrentStreak: 3,
          strCurrentStreak: "W 3",
        },
        {
          TeamID: 1610612737,
          TeamCity: "Atlanta",
          TeamName: "Hawks",
          TeamSlug: "hawks",
          Conference: "East",
          ConferenceRecord: "24-24",
          PlayoffRank: 8,
          Division: "Southeast",
          DivisionRank: 2,
          WINS: 39,
          LOSSES: 39,
          WinPCT: 0.5,
          HOME: "23-16",
          ROAD: "16-23",
          L10: "5-5  ",
          Last10Home: "6-4  ",
          Last10Road: "2-8  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612740,
          TeamCity: "New Orleans",
          TeamName: "Pelicans",
          TeamSlug: "pelicans",
          Conference: "West",
          ConferenceRecord: "28-21",
          PlayoffRank: 8,
          Division: "Southwest",
          DivisionRank: 2,
          WINS: 40,
          LOSSES: 38,
          WinPCT: 0.513,
          HOME: "25-13",
          ROAD: "15-25",
          L10: "7-3  ",
          Last10Home: "6-4  ",
          Last10Road: "5-5  ",
          CurrentStreak: 2,
          strCurrentStreak: "W 2",
        },
        {
          TeamID: 1610612750,
          TeamCity: "Minnesota",
          TeamName: "Timberwolves",
          TeamSlug: "timberwolves",
          Conference: "West",
          ConferenceRecord: "27-23",
          PlayoffRank: 9,
          Division: "Northwest",
          DivisionRank: 2,
          WINS: 39,
          LOSSES: 40,
          WinPCT: 0.494,
          HOME: "21-19",
          ROAD: "18-21",
          L10: "4-6  ",
          Last10Home: "2-8  ",
          Last10Road: "7-3  ",
          CurrentStreak: -3,
          strCurrentStreak: "L 3",
        },
        {
          TeamID: 1610612761,
          TeamCity: "Toronto",
          TeamName: "Raptors",
          TeamSlug: "raptors",
          Conference: "East",
          ConferenceRecord: "24-24",
          PlayoffRank: 9,
          Division: "Atlantic",
          DivisionRank: 5,
          WINS: 39,
          LOSSES: 39,
          WinPCT: 0.5,
          HOME: "26-14",
          ROAD: "13-25",
          L10: "7-3  ",
          Last10Home: "9-1  ",
          Last10Road: "3-7  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612741,
          TeamCity: "Chicago",
          TeamName: "Bulls",
          TeamSlug: "bulls",
          Conference: "East",
          ConferenceRecord: "26-23",
          PlayoffRank: 10,
          Division: "Central",
          DivisionRank: 3,
          WINS: 38,
          LOSSES: 40,
          WinPCT: 0.487,
          HOME: "21-18",
          ROAD: "17-22",
          L10: "7-3  ",
          Last10Home: "5-5  ",
          Last10Road: "7-3  ",
          CurrentStreak: 2,
          strCurrentStreak: "W 2",
        },
        {
          TeamID: 1610612760,
          TeamCity: "Oklahoma City",
          TeamName: "Thunder",
          TeamSlug: "thunder",
          Conference: "West",
          ConferenceRecord: "23-26",
          PlayoffRank: 10,
          Division: "Northwest",
          DivisionRank: 3,
          WINS: 38,
          LOSSES: 41,
          WinPCT: 0.481,
          HOME: "23-17",
          ROAD: "15-24",
          L10: "4-6  ",
          Last10Home: "6-4  ",
          Last10Road: "4-6  ",
          CurrentStreak: -2,
          strCurrentStreak: "L 2",
        },
        {
          TeamID: 1610612764,
          TeamCity: "Washington",
          TeamName: "Wizards",
          TeamSlug: "wizards",
          Conference: "East",
          ConferenceRecord: "20-29",
          PlayoffRank: 11,
          Division: "Southeast",
          DivisionRank: 3,
          WINS: 34,
          LOSSES: 44,
          WinPCT: 0.436,
          HOME: "18-20",
          ROAD: "16-24",
          L10: "3-7  ",
          Last10Home: "3-7  ",
          Last10Road: "4-6  ",
          CurrentStreak: -2,
          strCurrentStreak: "L 2",
        },
        {
          TeamID: 1610612742,
          TeamCity: "Dallas",
          TeamName: "Mavericks",
          TeamSlug: "mavericks",
          Conference: "West",
          ConferenceRecord: "27-23",
          PlayoffRank: 11,
          Division: "Southwest",
          DivisionRank: 3,
          WINS: 37,
          LOSSES: 42,
          WinPCT: 0.468,
          HOME: "22-16",
          ROAD: "15-26",
          L10: "3-7  ",
          Last10Home: "3-7  ",
          Last10Road: "3-7  ",
          CurrentStreak: -3,
          strCurrentStreak: "L 3",
        },
        {
          TeamID: 1610612762,
          TeamCity: "Utah",
          TeamName: "Jazz",
          TeamSlug: "jazz",
          Conference: "West",
          ConferenceRecord: "23-25",
          PlayoffRank: 12,
          Division: "Northwest",
          DivisionRank: 4,
          WINS: 36,
          LOSSES: 42,
          WinPCT: 0.462,
          HOME: "22-16",
          ROAD: "14-26",
          L10: "3-7  ",
          Last10Home: "4-6  ",
          Last10Road: "3-7  ",
          CurrentStreak: -2,
          strCurrentStreak: "L 2",
        },
        {
          TeamID: 1610612753,
          TeamCity: "Orlando",
          TeamName: "Magic",
          TeamSlug: "magic",
          Conference: "East",
          ConferenceRecord: "20-28",
          PlayoffRank: 12,
          Division: "Southeast",
          DivisionRank: 4,
          WINS: 34,
          LOSSES: 44,
          WinPCT: 0.436,
          HOME: "20-19",
          ROAD: "14-25",
          L10: "6-4  ",
          Last10Home: "6-4  ",
          Last10Road: "4-6  ",
          CurrentStreak: 2,
          strCurrentStreak: "W 2",
        },
        {
          TeamID: 1610612754,
          TeamCity: "Indiana",
          TeamName: "Pacers",
          TeamSlug: "pacers",
          Conference: "East",
          ConferenceRecord: "23-26",
          PlayoffRank: 13,
          Division: "Central",
          DivisionRank: 4,
          WINS: 34,
          LOSSES: 45,
          WinPCT: 0.43,
          HOME: "20-19",
          ROAD: "14-26",
          L10: "3-7  ",
          Last10Home: "3-7  ",
          Last10Road: "4-6  ",
          CurrentStreak: -1,
          strCurrentStreak: "L 1",
        },
        {
          TeamID: 1610612757,
          TeamCity: "Portland",
          TeamName: "Trail Blazers",
          TeamSlug: "blazers",
          Conference: "West",
          ConferenceRecord: "23-25",
          PlayoffRank: 13,
          Division: "Northwest",
          DivisionRank: 5,
          WINS: 33,
          LOSSES: 45,
          WinPCT: 0.423,
          HOME: "17-23",
          ROAD: "16-22",
          L10: "2-8  ",
          Last10Home: "1-9  ",
          Last10Road: "4-6  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612766,
          TeamCity: "Charlotte",
          TeamName: "Hornets",
          TeamSlug: "hornets",
          Conference: "East",
          ConferenceRecord: "14-36",
          PlayoffRank: 14,
          Division: "Southeast",
          DivisionRank: 5,
          WINS: 26,
          LOSSES: 53,
          WinPCT: 0.329,
          HOME: "13-26",
          ROAD: "13-27",
          L10: "4-6  ",
          Last10Home: "2-8  ",
          Last10Road: "5-5  ",
          CurrentStreak: -2,
          strCurrentStreak: "L 2",
        },
        {
          TeamID: 1610612759,
          TeamCity: "San Antonio",
          TeamName: "Spurs",
          TeamSlug: "spurs",
          Conference: "West",
          ConferenceRecord: "8-40 ",
          PlayoffRank: 14,
          Division: "Southwest",
          DivisionRank: 4,
          WINS: 20,
          LOSSES: 58,
          WinPCT: 0.256,
          HOME: "13-26",
          ROAD: "7-32 ",
          L10: "2-8  ",
          Last10Home: "4-6  ",
          Last10Road: "2-8  ",
          CurrentStreak: 1,
          strCurrentStreak: "W 1",
        },
        {
          TeamID: 1610612765,
          TeamCity: "Detroit",
          TeamName: "Pistons",
          TeamSlug: "pistons",
          Conference: "East",
          ConferenceRecord: "7-41 ",
          PlayoffRank: 15,
          Division: "Central",
          DivisionRank: 5,
          WINS: 16,
          LOSSES: 62,
          WinPCT: 0.205,
          HOME: "9-30 ",
          ROAD: "7-32 ",
          L10: "1-9  ",
          Last10Home: "1-9  ",
          Last10Road: "0-10 ",
          CurrentStreak: -9,
          strCurrentStreak: "L 9",
        },
        {
          TeamID: 1610612745,
          TeamCity: "Houston",
          TeamName: "Rockets",
          TeamSlug: "rockets",
          Conference: "West",
          ConferenceRecord: "11-40",
          PlayoffRank: 15,
          Division: "Southwest",
          DivisionRank: 5,
          WINS: 19,
          LOSSES: 60,
          WinPCT: 0.241,
          HOME: "13-27",
          ROAD: "6-33 ",
          L10: "2-8  ",
          Last10Home: "5-5  ",
          Last10Road: "1-9  ",
          CurrentStreak: -1,
          strCurrentStreak: "L 1",
        },
      ],
    };

    // const selectedHeaders = [
    //   "TeamID",
    //   "TeamCity",
    //   "TeamName",
    //   "TeamSlug",
    //   "Conference",
    //   "ConferenceRecord",
    //   "PlayoffRank",
    //   "Division",
    //   "DivisionRank",
    //   "WINS",
    //   "LOSSES",
    //   "WinPCT",
    //   "HOME",
    //   "ROAD",
    //   "L10",
    //   "Last10Home",
    //   "Last10Road",
    //   "CurrentStreak",
    //   "strCurrentStreak",
    // ];
    // const { headers, rowSet } = standings.resultSets[0];

    // const result = rowSet.map((row: any) =>
    //   row.reduce((obj: any, val: any, i: number) => {
    //     if (selectedHeaders.includes(headers[i])) {
    //       obj[headers[i]] = val;
    //     }
    //     return obj;
    //   }, {})
    // );

    // const data = {
    //   season: standings.parameters.SeasonYear,
    //   standings: result,
    // };

    // return data;
    return standings;
  } catch (error) {
    throw error;
  }
}
